[package]
name = "gym_tracker"
version = "0.1.0"
edition = "2024"

[workspace]
members = ["./entity", "api", "db", "migration"]

[workspace.dependencies]
anyhow = "1.0.98"
thiserror = "2.0.12"


[dependencies]
api = { path = "api" }
