[package]
name = "entity"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0.219", features = ["derive"] }
sea-orm = { version = "1.1.0", features = ["with-chrono", "with-json"] }
bcrypt = "0.17.0"
chrono = {version = "0.4.41", features = ["serde"] }
