[package]
name = "api"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-session = { version = "0.10.1", features = ["redis-session"] }
entity ={ path = "../entity" }
db = {path = "../db"}
serde = "1.0"
actix-web = "4"
sea-orm = "1.1.12"
regex = "1.11.1"
